export const GET_VIDEOS = 'GET_VIDEOS';
export const GET_MORE_VIDEOS = 'GET_MORE_VIDEOS';
export const GET_VIDEOS_REQUESTED = 'GET_VIDEOS_REQUESTED';
export const GET_MORE_VIDEOS_REQUESTED = 'GET_MORE_VIDEOS_REQUESTED';
export const SET_LOADING = 'SET_LOADING';
